"""
YouTube Comment Auto-Reply Bot
================================
Fetches recent comments on your YouTube channel and drafts/posts replies
generated by Claude, following the rules in config.py.

Usage:
    python bot.py

You shouldn't need to edit this file. All the customizable settings
live in config.py. See README.md for full setup instructions.
"""

import json
import os
import time
from datetime import datetime, timedelta, timezone

import anthropic
from dotenv import load_dotenv
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

import config

load_dotenv()

SCOPES = ["https://www.googleapis.com/auth/youtube.force-ssl"]
TOKEN_FILE = "token.json"
CLIENT_SECRET_FILE = "client_secret.json"
REPLIED_IDS_FILE = "replied_ids.json"
DRAFTS_FILE = "draft_replies.txt"


# ----------------------------------------------------------
# AUTH
# ----------------------------------------------------------

def get_youtube_client():
    """Logs in with Google (a browser tab opens on first run) and returns
    an authenticated YouTube API client. After the first run, the saved
    token.json is reused/refreshed automatically -- no repeat logins."""
    creds = None
    if os.path.exists(TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists(CLIENT_SECRET_FILE):
                raise FileNotFoundError(
                    f"Missing {CLIENT_SECRET_FILE}. Download it from Google Cloud "
                    "Console (README.md, Step 1) and put it in this folder."
                )
            flow = InstalledAppFlow.from_client_secrets_file(CLIENT_SECRET_FILE, SCOPES)
            creds = flow.run_local_server(port=0)
        with open(TOKEN_FILE, "w") as f:
            f.write(creds.to_json())

    return build("youtube", "v3", credentials=creds)


# ----------------------------------------------------------
# LOCAL STATE (which comments we've already handled)
# ----------------------------------------------------------

def load_replied_ids():
    if os.path.exists(REPLIED_IDS_FILE):
        with open(REPLIED_IDS_FILE) as f:
            return set(json.load(f))
    return set()


def save_replied_ids(ids):
    with open(REPLIED_IDS_FILE, "w") as f:
        json.dump(sorted(ids), f, indent=2)


# ----------------------------------------------------------
# YOUTUBE DATA
# ----------------------------------------------------------

def get_my_channel_id(youtube):
    res = youtube.channels().list(part="id", mine=True).execute()
    return res["items"][0]["id"]


def fetch_recent_comments(youtube, channel_id, replied_ids):
    """Pulls the most recent comments across the whole channel, newest
    first, and stops early once it reaches a comment already handled in
    a previous run -- keeps every run cheap on API quota."""
    comments = []
    page_token = None

    for _ in range(config.MAX_PAGES_PER_RUN):
        try:
            response = youtube.commentThreads().list(
                part="snippet",
                allThreadsRelatedToChannelId=channel_id,
                order="time",
                maxResults=100,
                textFormat="plainText",
                pageToken=page_token,
            ).execute()
        except HttpError as e:
            print(f"Couldn't fetch comments: {e}")
            break

        reached_known_comment = False
        for item in response.get("items", []):
            top = item["snippet"]["topLevelComment"]
            comment_id = top["id"]
            if comment_id in replied_ids:
                reached_known_comment = True
                break
            comments.append({
                "comment_id": comment_id,
                "text": top["snippet"]["textDisplay"],
                "author": top["snippet"]["authorDisplayName"],
                "video_id": top["snippet"]["videoId"],
                "total_replies": item["snippet"]["totalReplyCount"],
            })

        if reached_known_comment:
            break

        page_token = response.get("nextPageToken")
        if not page_token:
            break

    return comments


def filter_by_video_age(youtube, comments):
    """Drops comments left on videos older than ONLY_RECENT_VIDEO_DAYS.
    A no-op if that setting is None."""
    if config.ONLY_RECENT_VIDEO_DAYS is None or not comments:
        return comments

    video_ids = list({c["video_id"] for c in comments})
    published_at = {}

    for i in range(0, len(video_ids), 50):
        batch = video_ids[i:i + 50]
        try:
            response = youtube.videos().list(part="snippet", id=",".join(batch)).execute()
        except HttpError as e:
            print(f"Couldn't check video ages, skipping the age filter this run: {e}")
            return comments
        for item in response.get("items", []):
            published_at[item["id"]] = item["snippet"]["publishedAt"]

    cutoff = datetime.now(timezone.utc) - timedelta(days=config.ONLY_RECENT_VIDEO_DAYS)
    kept = []
    for c in comments:
        pub = published_at.get(c["video_id"])
        if pub and datetime.fromisoformat(pub.replace("Z", "+00:00")) >= cutoff:
            kept.append(c)
    return kept


def channel_already_replied(youtube, comment_id, channel_id):
    """True only if the CHANNEL OWNER has already replied to this thread
    (as opposed to some other viewer replying, which shouldn't stop us)."""
    try:
        response = youtube.comments().list(
            part="snippet", parentId=comment_id, maxResults=50,
        ).execute()
    except HttpError:
        return False
    return any(
        reply["snippet"].get("authorChannelId", {}).get("value") == channel_id
        for reply in response.get("items", [])
    )


def post_reply(youtube, comment_id, text):
    youtube.comments().insert(
        part="snippet",
        body={"snippet": {"parentId": comment_id, "textOriginal": text}},
    ).execute()


# ----------------------------------------------------------
# FILTERS + REPLY GENERATION
# ----------------------------------------------------------

def should_skip(comment):
    if len(comment["text"].strip()) < config.MIN_COMMENT_LENGTH:
        return True
    text_lower = comment["text"].lower()
    return any(kw.lower() in text_lower for kw in config.SKIP_KEYWORDS)


def check_faq(comment_text):
    text_lower = comment_text.lower()
    for trigger, response in config.FAQ_RESPONSES.items():
        if trigger.lower() in text_lower:
            return response
    return None


def generate_reply(client, comment_text, author):
    prompt = (
        f"{config.PERSONA}\n\n"
        f'A viewer named "{author}" left this comment: "{comment_text}"\n\n'
        "Write ONLY the reply text. No quotation marks, no preamble."
    )
    message = client.messages.create(
        model=config.CLAUDE_MODEL,
        max_tokens=150,
        messages=[{"role": "user", "content": prompt}],
    )
    return message.content[0].text.strip()


# ----------------------------------------------------------
# MAIN
# ----------------------------------------------------------

def main():
    if not os.environ.get("ANTHROPIC_API_KEY"):
        raise EnvironmentError(
            "ANTHROPIC_API_KEY is not set. Copy .env.example to .env and add your key."
        )

    claude = anthropic.Anthropic()
    youtube = get_youtube_client()
    channel_id = get_my_channel_id(youtube)
    replied_ids = load_replied_ids()

    print("Checking for new comments...")
    comments = fetch_recent_comments(youtube, channel_id, replied_ids)
    comments = filter_by_video_age(youtube, comments)
    print(f"Found {len(comments)} comment(s) to consider.")

    replies_made = 0
    draft_lines = []

    for comment in comments:
        if replies_made >= config.MAX_REPLIES_PER_RUN:
            print(f"Hit MAX_REPLIES_PER_RUN ({config.MAX_REPLIES_PER_RUN}) -- "
                  "stopping here for this run, the rest will be picked up next time.")
            break

        if should_skip(comment):
            replied_ids.add(comment["comment_id"])
            continue

        if comment["total_replies"] > 0 and channel_already_replied(
            youtube, comment["comment_id"], channel_id
        ):
            replied_ids.add(comment["comment_id"])
            continue

        faq_answer = check_faq(comment["text"])
        try:
            reply_text = faq_answer or generate_reply(claude, comment["text"], comment["author"])
        except Exception as e:
            print(f"Couldn't generate a reply for comment {comment['comment_id']}: {e}")
            continue

        if config.DRAFT_MODE:
            draft_lines.append(
                f"From: {comment['author']}\n"
                f"Comment: {comment['text']}\n"
                f"Proposed reply: {reply_text}\n"
                f"Link: https://youtube.com/watch?v={comment['video_id']}&lc={comment['comment_id']}\n"
                + "-" * 60
            )
        else:
            try:
                post_reply(youtube, comment["comment_id"], reply_text)
                print(f"Replied to {comment['author']}: {reply_text}")
                time.sleep(1)  # be gentle, avoid bursts
            except HttpError as e:
                print(f"Failed to post reply to {comment['comment_id']}: {e}")
                continue

        replied_ids.add(comment["comment_id"])
        replies_made += 1

    if config.DRAFT_MODE and draft_lines:
        with open(DRAFTS_FILE, "a") as f:
            f.write(f"\n=== Run at {datetime.now().isoformat(timespec='seconds')} ===\n")
            f.write("\n".join(draft_lines) + "\n")
        plural = "y" if len(draft_lines) == 1 else "ies"
        print(f"Wrote {len(draft_lines)} draft repl{plural} to {DRAFTS_FILE} for you to review.")
    elif not config.DRAFT_MODE:
        plural = "y" if replies_made == 1 else "ies"
        print(f"Posted {replies_made} repl{plural} live.")

    save_replied_ids(replied_ids)
    print("Done.")


if __name__ == "__main__":
    main()
